apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: spark
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: spark
    spec:
      containers:
        - env:
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_MODE
              value: master
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: MONGODB_HOST
              value: "mongodb-dev.default.svc.cluster.local"
            - name: MONGODB_PORT
              value: "27017"
            - name: BOOTSTRAP_SERVERS
              value: "my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092"
            - name: SEND_PREDICTION_TO
              value: "mongo"
          image: crimson160/practica_fbid:spark
          name: spark-m
          ports:
            - containerPort: 7077
          resources: {}
      #imagePullSecrets:      
      #- name: regcred
      restartPolicy: Always
status: {}


